DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    USER_ID LONG AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR (100),
    PHONE_NUMBER VARCHAR(10)
);
